### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by n2fole00** [dfpeterson/GetDuolingoNotes#1]
I tried with the current instructions, but got this...

```
Uncaught TypeError: Cannot read property 'querySelector' of undefined(…)
```

I found I had to select one of the lessons and then go back to the home page in order for the script to work.

**Comment by dfpeterson** [comment]
What OS are you running?

**Comment by n2fole00** [comment]
Ubuntu Linux 14.04

I've just tried on Windows 8.1 and it worked fine first time (straight after login).

**Comment by dfpeterson** [comment]
Sorry for the delay. When you are running it on ubuntu, does it tell you a line and character where it is failing? Unfortunately I don't have ubuntu so I don't have the capability to debug it easily.

**Comment by n2fole00** [comment]
No problem. I've just tried to reproduce the error again and couldn't! I tried clearing browser cookies too. 

Sorry I couldn't be more help.  Perhaps it's something that has been changed recently in Chrome or on the DuoLingo site.

**Comment by n2fole00** [comment]
No problem. I've just tried to reproduce the error again and couldn't! I tried clearing browser cookies too.

Sorry I couldn't be more help. Perhaps it's something that has been changed recently in Chrome or on the DuoLingo site.
